local:
  server:
    port: 8080
  postgres:
    host: "localhost"
    port: 6432
    user: "postgres"
    password:  "postgres"
    name: "mockidoki"
  kafka:
    broker: test-infra-service.svc.dev-1-hq:9092

