apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orange
  name: ${CI_PROJECT_NAME}-deployment
  labels:
    app: ${CI_PROJECT_NAME}
spec:
  replicas: ${MIN_REPLICAS}
  selector:
    matchLabels:
      app: ${CI_PROJECT_NAME}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    metadata:
      labels:
        app: ${CI_PROJECT_NAME}
    spec:
      containers:
        - name: ${CI_PROJECT_NAME}
          image: ${DOCKER_IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: ${MEMORY_REQUEST}
              cpu: ${CPU_REQUEST}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
          readinessProbe:
            httpGet:
              path: /management/health
              port: 8080
            timeoutSeconds: 10
            periodSeconds: 10
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /management/health
              port: 8080
            timeoutSeconds: 20
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 5
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: ${GITLAB_REGISTRY_SECRET_NAME}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - ${CI_PROJECT_NAME}
                topologyKey: "kubernetes.io/hostname"
